# MLP regressor demo

### Import Packages Etc

In [1]:
from IPython.display import display, HTML, Image

from MLP import MultiLayerPerceptron

import numpy as np

import math

### Generate Test Data

Generating 50 input vectors each containing 4 random number components, with a corresponding output of the following formula: 

For inputs [x1 x2 x3 x4], output = sin(x1-x2+x3-x4) 

In [2]:
Input = np.random.normal(loc=0.0, scale=0.3, size=(50, 4))
print(Input)

[[ 2.76289114e-01  7.68256160e-02 -5.37821094e-02  4.41799315e-01]
 [-1.58943254e-01  1.24391622e-01 -2.12542534e-01 -3.98515484e-01]
 [-1.72697044e-01 -9.38855558e-02 -3.70321133e-01 -2.55172711e-01]
 [-4.07261016e-02 -6.29048441e-02 -9.87975460e-02 -1.43697127e-01]
 [-2.32131686e-01  3.68663332e-01 -4.52437441e-01 -2.58869622e-01]
 [-7.19476632e-01 -2.36927444e-01 -7.62486402e-02 -3.10420577e-01]
 [-8.15001792e-01 -3.24816724e-01  2.07797245e-01 -1.31364656e-01]
 [-3.29678772e-01 -3.53085218e-01 -4.64600359e-01 -2.43990027e-02]
 [ 4.82609397e-02 -2.01350344e-01  1.45023994e-01  2.51736152e-01]
 [ 5.01503431e-02 -2.27774675e-01 -3.13577549e-01  1.13218515e-01]
 [-1.33960474e-02 -3.77164193e-02 -3.15820495e-01  3.10260478e-01]
 [-1.90796429e-01 -3.68490937e-02 -5.94751405e-03  1.94331199e-01]
 [ 5.70121470e-02  7.67328242e-01 -1.46943425e-01 -1.91912712e-04]
 [-5.58680040e-02 -3.16366420e-01  5.79188780e-01 -2.76449106e-01]
 [ 1.56437224e-01 -1.00673089e-02  3.44374435e-01 -1.84934643e

In [3]:
Output = np.array([[]], float)
for row in Input:
    temp = np.sin(row[0]-row[1]+row[2]-row[3])
    Output = np.append(Output, temp)
print(Output)

[-0.2918093  -0.09720818 -0.19274605  0.06702803 -0.71341726 -0.24583133
 -0.15044973 -0.40483183  0.14241328 -0.14832176 -0.56609468 -0.34686457
 -0.7559261   0.89841038  0.64101012 -0.31058824  0.69935621 -0.68917065
  0.7878241   0.66467561  0.41793768  0.02041284  0.11028407 -0.15006195
  0.05888697 -0.00699407 -0.75529885 -0.2608794  -0.61991412 -0.64926812
  0.68914849 -0.5903258  -0.52375706 -0.51538083  0.18229028  0.61767624
  0.10116959 -0.08097808 -0.24936398 -0.37906441 -0.45499283 -0.3824622
  0.46075224  0.25925104  0.4192218  -0.06809566  0.63977036  0.57041477
  0.28242448  0.11132513]


In [4]:
Output = Output.reshape(50,1)
print(Output.shape)
print(Output)

(50, 1)
[[-0.2918093 ]
 [-0.09720818]
 [-0.19274605]
 [ 0.06702803]
 [-0.71341726]
 [-0.24583133]
 [-0.15044973]
 [-0.40483183]
 [ 0.14241328]
 [-0.14832176]
 [-0.56609468]
 [-0.34686457]
 [-0.7559261 ]
 [ 0.89841038]
 [ 0.64101012]
 [-0.31058824]
 [ 0.69935621]
 [-0.68917065]
 [ 0.7878241 ]
 [ 0.66467561]
 [ 0.41793768]
 [ 0.02041284]
 [ 0.11028407]
 [-0.15006195]
 [ 0.05888697]
 [-0.00699407]
 [-0.75529885]
 [-0.2608794 ]
 [-0.61991412]
 [-0.64926812]
 [ 0.68914849]
 [-0.5903258 ]
 [-0.52375706]
 [-0.51538083]
 [ 0.18229028]
 [ 0.61767624]
 [ 0.10116959]
 [-0.08097808]
 [-0.24936398]
 [-0.37906441]
 [-0.45499283]
 [-0.3824622 ]
 [ 0.46075224]
 [ 0.25925104]
 [ 0.4192218 ]
 [-0.06809566]
 [ 0.63977036]
 [ 0.57041477]
 [ 0.28242448]
 [ 0.11132513]]


### Training at an 80:20 train/test split

In [5]:
# split data into test/training sets
XTest = Input[40:,:]
XTrain = Input[:40,:]

YTest = Output[40:,:]
YTrain = Output[:40,:]

In [6]:
mlp_3 = MultiLayerPerceptron(hidden_units = 16, epochs = 100000, weights_range = 'xavier', \
                         batch_size = 8, random_seed = 23, verbose = 0)
mlp_3.fit(XTrain, YTrain)

MSE for epoch 5000 is 0.00017737429139337194 	 MAE is 0.014267650563014229
MSE for epoch 10000 is 0.0001768507115705052 	 MAE is 0.014245878961785035
MSE for epoch 15000 is 0.0001746324539219666 	 MAE is 0.0141865111997212
MSE for epoch 20000 is 0.0001730389586723875 	 MAE is 0.014150298632652164
MSE for epoch 25000 is 0.00017147833403834438 	 MAE is 0.014077601228586223
MSE for epoch 30000 is 0.0001704279461364117 	 MAE is 0.01405407305486948
MSE for epoch 35000 is 0.00016856706293893233 	 MAE is 0.013985268455578681
MSE for epoch 40000 is 0.00016648011681795794 	 MAE is 0.013882968257674011
MSE for epoch 45000 is 0.00016571489897303663 	 MAE is 0.013893437268412145
MSE for epoch 50000 is 0.00016273385242519773 	 MAE is 0.013768372432955417
MSE for epoch 55000 is 0.00016106299057388739 	 MAE is 0.013675618673552584
MSE for epoch 60000 is 0.00015950350057260382 	 MAE is 0.013642976374371308
MSE for epoch 65000 is 0.00015727030728342558 	 MAE is 0.013556298048276091
MSE for epoch 70000 

In [7]:
print("Test set actual outputs: \n", YTest)
XTest_predict = mlp_3.predict(XTest)

print()
print("Test set predictions: \n", XTest_predict)

Test set actual outputs: 
 [[-0.45499283]
 [-0.3824622 ]
 [ 0.46075224]
 [ 0.25925104]
 [ 0.4192218 ]
 [-0.06809566]
 [ 0.63977036]
 [ 0.57041477]
 [ 0.28242448]
 [ 0.11132513]]

Test set predictions: 
 [[-0.43604984]
 [-0.37264287]
 [ 0.42793408]
 [ 0.23759073]
 [ 0.39431949]
 [-0.07092051]
 [ 0.61962853]
 [ 0.54962367]
 [ 0.25696101]
 [ 0.09431486]]


In [8]:
mse, mae, ae = mlp_3.calculate_error(YTest, XTest_predict, XTest_predict.shape[0])
print("MSE on test is", mse)
print("MAE on test is", mae)

MSE on test is 0.00022026310374649414
MAE on test is 0.01943746220290816
